spring.datasource.url=jdbc:mysql://localhost:3306/qaute?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=12345
spring.mail.host=smtp.gmail.com
spring.mail.username=llthanhtoan@gmail.com
spring.mail.password=hawkgillbxvgbnpr
app.base-url=http://localhost:8080
app.jwt.secret=dev-only-secret-key-qaute-0123456789-0123456789-abcdef
app.otp.hmac-secret=dev-only-otp-hmac-secret-qaute
cloudinary.url=cloudinary://971596393999274:YwTpCA8ium1FD7A8nVwfsxP45Ig@ccgkesp4
logging.level.vn.edu.hcmute.qaute=DEBUG
