CREATE TABLE system_settings (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    setting_key   VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    value_type    VARCHAR(20)  NOT NULL,
    min_value     BIGINT       NULL,
    max_value     BIGINT       NULL,
    group_name    VARCHAR(50)  NOT NULL,
    description   VARCHAR(300) NOT NULL,
    updated_by    BIGINT       NULL,
    created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_system_settings_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO system_settings
    (setting_key, setting_value, value_type, min_value, max_value, group_name, description)
VALUES
    ('otp.ttl.minutes', '5', 'INT', 1, 60, 'OTP', 'Thời gian hiệu lực mã OTP tính theo phút'),
    ('otp.max.attempts', '5', 'INT', 1, 10, 'OTP', 'Số lần nhập sai OTP tối đa'),
    ('otp.resend.cooldown.seconds', '60', 'INT', 10, 600, 'OTP', 'Thời gian chờ giữa hai lần gửi lại OTP'),
    ('otp.max.send.per.hour', '5', 'INT', 1, 20, 'OTP', 'Số lần gửi OTP tối đa trong một giờ'),
    ('auth.access.ttl.minutes', '15', 'INT', 5, 120, 'BẢO MẬT', 'Thời gian sống của access token tính theo phút'),
    ('auth.refresh.ttl.days', '7', 'INT', 1, 30, 'BẢO MẬT', 'Thời gian sống của refresh token tính theo ngày'),
    ('auth.refresh.remember.ttl.days', '30', 'INT', 1, 90, 'BẢO MẬT', 'Thời gian sống refresh token khi ghi nhớ đăng nhập'),
    ('auth.max.failed.logins', '5', 'INT', 3, 20, 'BẢO MẬT', 'Số lần đăng nhập sai tối đa'),
    ('auth.lock.minutes', '15', 'INT', 1, 1440, 'BẢO MẬT', 'Thời gian khóa tài khoản tính theo phút'),
    ('auth.unverified.cleanup.hours', '24', 'INT', 1, 168, 'BẢO MẬT', 'Thời gian dọn tài khoản chưa xác minh tính theo giờ'),
    ('ticket.urgent.request.limit', '2', 'INT', 0, 10, 'TICKET', 'Số yêu cầu khẩn cấp tối đa'),
    ('ticket.auto.close.resolved.days', '3', 'INT', 1, 30, 'TICKET', 'Số ngày tự đóng yêu cầu đã giải quyết'),
    ('ticket.auto.close.waiting.days', '7', 'INT', 1, 60, 'TICKET', 'Số ngày tự đóng yêu cầu chờ sinh viên'),
    ('ticket.reopen.window.days', '7', 'INT', 1, 60, 'TICKET', 'Khoảng thời gian cho phép mở lại yêu cầu'),
    ('ticket.reopen.max', '2', 'INT', 0, 10, 'TICKET', 'Số lần mở lại yêu cầu tối đa'),
    ('ticket.rating.edit.days', '7', 'INT', 0, 60, 'TICKET', 'Số ngày cho phép chỉnh sửa đánh giá'),
    ('ticket.auto.assign.enabled', 'false', 'BOOL', NULL, NULL, 'TICKET', 'Bật tự động phân công yêu cầu'),
    ('sla.at.risk.percent', '80', 'INT', 50, 99, 'SLA', 'Ngưỡng phần trăm cảnh báo sắp quá hạn'),
    ('file.max.count', '5', 'INT', 1, 10, 'TỆP', 'Số tệp đính kèm tối đa'),
    ('file.max.size.mb', '10', 'INT', 1, 50, 'TỆP', 'Dung lượng mỗi tệp tối đa tính theo MB'),
    ('file.max.total.mb', '25', 'INT', 1, 100, 'TỆP', 'Tổng dung lượng tệp tối đa tính theo MB'),
    ('chat.max.concurrent', '3', 'INT', 1, 10, 'CHAT', 'Số phiên chat đồng thời tối đa'),
    ('chat.waiting.timeout.minutes', '10', 'INT', 1, 60, 'CHAT', 'Thời gian chờ chat tối đa tính theo phút'),
    ('chat.idle.timeout.minutes', '15', 'INT', 1, 120, 'CHAT', 'Thời gian chat không hoạt động trước khi hết hạn'),
    ('chat.message.max.length', '1000', 'INT', 100, 5000, 'CHAT', 'Độ dài tin nhắn chat tối đa'),
    ('chat.use.business.hours', 'true', 'BOOL', NULL, NULL, 'CHAT', 'Giới hạn chat theo giờ làm việc'),
    ('appointment.slot.minutes', '30', 'INT', 15, 120, 'LỊCH HẸN', 'Thời lượng một khung giờ hẹn tính theo phút'),
    ('appointment.lead.hours', '12', 'INT', 0, 168, 'LỊCH HẸN', 'Thời gian báo trước khi đặt lịch tính theo giờ'),
    ('appointment.cancel.before.hours', '6', 'INT', 0, 168, 'LỊCH HẸN', 'Thời gian tối thiểu trước lịch hẹn để hủy'),
    ('appointment.max.upcoming', '2', 'INT', 1, 10, 'LỊCH HẸN', 'Số lịch hẹn sắp tới tối đa'),
    ('appointment.generate.days', '30', 'INT', 7, 90, 'LỊCH HẸN', 'Số ngày tạo khung giờ hẹn'),
    ('faq.view.dedupe.minutes', '30', 'INT', 1, 1440, 'FAQ', 'Thời gian chống ghi nhận lượt xem trùng'),
    ('page.size.default', '10', 'INT', 5, 50, 'CHUNG', 'Kích thước trang mặc định'),
    ('page.size.max', '100', 'INT', 10, 200, 'CHUNG', 'Kích thước trang tối đa'),
    ('retention.notification.days', '90', 'INT', 7, 730, 'LƯU TRỮ', 'Thời gian lưu thông báo tính theo ngày'),
    ('retention.search.logs.days', '180', 'INT', 7, 730, 'LƯU TRỮ', 'Thời gian lưu nhật ký tìm kiếm tính theo ngày'),
    ('retention.login.history.days', '180', 'INT', 7, 730, 'LƯU TRỮ', 'Thời gian lưu lịch sử đăng nhập tính theo ngày'),
    ('retention.audit.days', '365', 'INT', 30, 3650, 'LƯU TRỮ', 'Thời gian lưu nhật ký audit tính theo ngày'),
    ('cloudinary.signed.url.ttl.minutes', '5', 'INT', 1, 60, 'TỆP', 'Thời gian sống URL Cloudinary có chữ ký'),
    ('site.contact.email', 'tuvan@hcmute.edu.vn', 'STRING', NULL, NULL, 'LIÊN HỆ', 'Địa chỉ email liên hệ'),
    ('site.contact.phone', '(028) 3722 0000', 'STRING', NULL, NULL, 'LIÊN HỆ', 'Số điện thoại liên hệ'),
    ('site.contact.address', '1 Võ Văn Ngân, TP. Thủ Đức, TP.HCM', 'STRING', NULL, NULL, 'LIÊN HỆ', 'Địa chỉ liên hệ');
