CREATE TABLE media_assets (
    id                 BIGINT       NOT NULL AUTO_INCREMENT,
    public_id          VARCHAR(255) NOT NULL,
    resource_type      VARCHAR(20)  NOT NULL,
    delivery_type      VARCHAR(20)  NOT NULL,
    mime_type          VARCHAR(100) NOT NULL,
    size_bytes         BIGINT       NOT NULL,
    width              INT          NULL,
    height             INT          NULL,
    original_filename  VARCHAR(255) NOT NULL,
    checksum_sha256    VARCHAR(64)  NULL,
    folder             VARCHAR(150) NOT NULL,
    owner_id           BIGINT       NULL,
    usage_type         VARCHAR(30)  NOT NULL,
    usage_ref_id       BIGINT       NULL,
    secure_url         VARCHAR(500) NULL,
    status             VARCHAR(10)  NOT NULL,
    created_at         DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at         DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_media_assets_public_id (public_id),
    KEY idx_media_assets_usage (usage_type, usage_ref_id),
    KEY idx_media_assets_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
